[package]
name = "prediction_market"
version = "1.0.0"

[addresses]
prediction_market = "0x8b421ba847e4a8bb1726290fe9928f19290225fb1424f8b18f70116b61138343"

[dev-addresses]
prediction_market = "0x123"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
